services: 
  node1:
      image: node:22-alpine
      container_name: node1
      restart: always
      networks: [webnet]
      ports:
        - "3000:3000"
      volumes:
        - ./sites/site1/dropadox:/usr/src/app
      working_dir: /usr/src/app
      env_file:
        - ./sites/site1/dropadox/.env
      command: sh -c "npm install && npm run build && node .output/server/index.mjs"

